version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - cd my-react-app
      - npm install
  build:
    commands:
      - CI=false npm test -- --coverage
artifacts:
  base-directory: my-react-app/build
  files:
    - "**/*"
